"""initial schema

Revision ID: 4d76cdc4174c
Revises: 
Create Date: 2026-07-21 00:31:21.845626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d76cdc4174c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('support_level', sa.String(), nullable=True),
    sa.Column('is_tracked', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tickets_checked', sa.Integer(), nullable=False),
    sa.Column('tickets_updated', sa.Integer(), nullable=False),
    sa.Column('events_ingested', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.CheckConstraint("run_type IN ('manual','scheduled','add_ticket','backfill')", name='ck_sync_run_type'),
    sa.CheckConstraint("status IN ('running','success','partial_failure','error')", name='ck_sync_run_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_state',
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('last_full_backfill_at', sa.DateTime(), nullable=True),
    sa.Column('last_incremental_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_incremental_sync_status', sa.String(), nullable=True),
    sa.Column('last_incremental_sync_error', sa.Text(), nullable=True),
    sa.Column('next_poll_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('scope')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('tag_type_mappings',
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('type_label', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('assigned_agent_id', sa.String(), nullable=True),
    sa.Column('assigned_to_email', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('tags_cache', sa.JSON(), nullable=True),
    sa.Column('tag_ids_cache', sa.JSON(), nullable=True),
    sa.Column('derived_type', sa.String(), nullable=True),
    sa.Column('overwatch_status', sa.String(), nullable=True),
    sa.Column('ticket_custom_fields', sa.JSON(), nullable=True),
    sa.Column('thread_total_events', sa.Integer(), nullable=True),
    sa.Column('thread_messages', sa.Integer(), nullable=True),
    sa.Column('thread_notes', sa.Integer(), nullable=True),
    sa.Column('thread_system_events', sa.Integer(), nullable=True),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.Column('created_at_trinity', sa.DateTime(), nullable=False),
    sa.Column('updated_at_trinity', sa.DateTime(), nullable=False),
    sa.Column('last_customer_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=False),
    sa.Column('first_assigned_to_agent_at', sa.DateTime(), nullable=True),
    sa.Column('trinity_url', sa.String(), nullable=True),
    sa.Column('added_to_tracker_at', sa.DateTime(), nullable=False),
    sa.Column('is_tracked', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('OPEN','PENDING','CLOSED','REJECTED','BLOCKED')", name='ck_ticket_status'),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num')
    )
    op.create_index('idx_tickets_assigned', 'tickets', ['assigned_agent_id'], unique=False)
    op.create_index('idx_tickets_last_event', 'tickets', ['last_event_at'], unique=False)
    op.create_index('idx_tickets_status', 'tickets', ['status'], unique=False)
    op.create_index('idx_tickets_type', 'tickets', ['derived_type'], unique=False)
    op.create_table('local_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('agent_email', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_local_notes_ticket', 'local_notes', ['ticket_id', 'created_at'], unique=False)
    op.create_table('ticket_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('ticket_num', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_email', sa.String(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("direction IN ('inbound','outbound') OR direction IS NULL", name='ck_event_direction'),
    sa.CheckConstraint("type IN ('message','audit','note','ai_draft')", name='ck_event_type'),
    sa.CheckConstraint("visibility IN ('public','internal') OR visibility IS NULL", name='ck_event_visibility'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'seq', name='uq_ticket_seq')
    )
    op.create_index('idx_events_created_at', 'ticket_events', ['created_at'], unique=False)
    op.create_index('idx_events_ticket_seq', 'ticket_events', ['ticket_id', 'seq'], unique=False)
    op.create_index('idx_events_type_action', 'ticket_events', ['type', 'action'], unique=False)
    op.create_table('ticket_tags',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id')
    )
    op.create_table('csat_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('close_cycle_index', sa.Integer(), nullable=True),
    sa.Column('csat_survey_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('csat_sent','csat_cancelled')", name='ck_csat_action'),
    sa.ForeignKeyConstraint(['event_id'], ['ticket_events.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('status_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('ticket_num', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('is_close', sa.Boolean(), nullable=False),
    sa.Column('is_reopen', sa.Boolean(), nullable=False),
    sa.Column('is_customer_triggered_reopen', sa.Boolean(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('agent_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ticket_events.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_st_close_date', 'status_transitions', ['is_close', 'event_date'], unique=False)
    op.create_index('idx_st_date', 'status_transitions', ['event_date'], unique=False)
    op.create_index('idx_st_reopen_date', 'status_transitions', ['is_reopen', 'event_date'], unique=False)
    op.create_index('idx_st_ticket', 'status_transitions', ['ticket_id', 'seq'], unique=False)
    op.create_table('ticket_duplicates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('duplicate_of_num', sa.Integer(), nullable=False),
    sa.Column('detected_from_event_id', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['detected_from_event_id'], ['ticket_events.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_duplicates')
    op.drop_index('idx_st_ticket', table_name='status_transitions')
    op.drop_index('idx_st_reopen_date', table_name='status_transitions')
    op.drop_index('idx_st_date', table_name='status_transitions')
    op.drop_index('idx_st_close_date', table_name='status_transitions')
    op.drop_table('status_transitions')
    op.drop_table('csat_events')
    op.drop_table('ticket_tags')
    op.drop_index('idx_events_type_action', table_name='ticket_events')
    op.drop_index('idx_events_ticket_seq', table_name='ticket_events')
    op.drop_index('idx_events_created_at', table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index('idx_local_notes_ticket', table_name='local_notes')
    op.drop_table('local_notes')
    op.drop_index('idx_tickets_type', table_name='tickets')
    op.drop_index('idx_tickets_status', table_name='tickets')
    op.drop_index('idx_tickets_last_event', table_name='tickets')
    op.drop_index('idx_tickets_assigned', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('tag_type_mappings')
    op.drop_table('tags')
    op.drop_table('sync_state')
    op.drop_table('sync_runs')
    op.drop_table('settings')
    op.drop_table('customers')
    op.drop_table('agents')
    # ### end Alembic commands ###
