"""add roster agents and shifts

Revision ID: 84dc3b668cfc
Revises: db18e4a748ce
Create Date: 2026-07-21 19:28:25.953459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '84dc3b668cfc'
down_revision: Union[str, None] = 'db18e4a748ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_agents',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('roster_shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_email', sa.String(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_email'], ['roster_agents.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_email', 'shift_date', name='uq_roster_shift_agent_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster_shifts')
    op.drop_table('roster_agents')
    # ### end Alembic commands ###
