"""add assignment events

Revision ID: a894dd12a160
Revises: 4d76cdc4174c
Create Date: 2026-07-21 11:58:32.856190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a894dd12a160'
down_revision: Union[str, None] = '4d76cdc4174c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('ticket_num', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_assignee', sa.String(), nullable=True),
    sa.Column('new_assignee', sa.String(), nullable=True),
    sa.Column('is_gain_for_tracked_agent', sa.Boolean(), nullable=False),
    sa.Column('is_taken_from_tracked_agent', sa.Boolean(), nullable=False),
    sa.Column('is_system_action', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('performed_by_email', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('assigned','unassigned')", name='ck_assignment_action'),
    sa.ForeignKeyConstraint(['event_id'], ['ticket_events.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_ae_taken_date', 'assignment_events', ['is_taken_from_tracked_agent', 'event_date'], unique=False)
    op.create_index('idx_ae_ticket_seq', 'assignment_events', ['ticket_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ae_ticket_seq', table_name='assignment_events')
    op.drop_index('idx_ae_taken_date', table_name='assignment_events')
    op.drop_table('assignment_events')
    # ### end Alembic commands ###
