"""add otp codes

Revision ID: db18e4a748ce
Revises: a894dd12a160
Create Date: 2026-07-21 12:29:03.189334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db18e4a748ce'
down_revision: Union[str, None] = 'a894dd12a160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_email_created', 'otp_codes', ['email', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_otp_email_created', table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
