"""add level transitions and self release flag

Revision ID: dcec4998b905
Revises: 84dc3b668cfc
Create Date: 2026-07-22 01:28:34.566043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dcec4998b905'
down_revision: Union[str, None] = '84dc3b668cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('ticket_num', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('old_level', sa.String(), nullable=True),
    sa.Column('new_level', sa.String(), nullable=True),
    sa.Column('is_escalation', sa.Boolean(), nullable=False),
    sa.Column('is_deescalation', sa.Boolean(), nullable=False),
    sa.Column('is_system_action', sa.Boolean(), nullable=False),
    sa.Column('performed_by_email', sa.String(), nullable=True),
    sa.Column('possible_reason', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ticket_events.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_lt_deescalation_date', 'level_transitions', ['is_deescalation', 'event_date'], unique=False)
    op.create_index('idx_lt_escalation_date', 'level_transitions', ['is_escalation', 'event_date'], unique=False)
    op.create_index('idx_lt_ticket', 'level_transitions', ['ticket_id', 'seq'], unique=False)
    op.add_column(
        'assignment_events',
        sa.Column('is_self_release_for_tracked_agent', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_events', 'is_self_release_for_tracked_agent')
    op.drop_index('idx_lt_ticket', table_name='level_transitions')
    op.drop_index('idx_lt_escalation_date', table_name='level_transitions')
    op.drop_index('idx_lt_deescalation_date', table_name='level_transitions')
    op.drop_table('level_transitions')
    # ### end Alembic commands ###
